apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev
    build:
      local:
        push: true # true: 서버 테스트 / false: 로컬 테스트
      artifacts:
        # - image: feet312/sample-api # on dev server
        - image: docker-signet.sk.com/onm/onm-web 
          jib:
            args:
              - -DskipTests
              - "-Dgs ${maven_settings}"
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: docker-signet.sk.com/onm/cpos-jre-runtime:v1.0.0
  - name: stage
    build:
      local:
        push: true # true: 서버 테스트 / false: 로컬 테스트
      artifacts:
        # - image: feet312/sample-api # on dev server
        - image: docker-signet.sk.com/onm/onm-web 
          jib:
            args:
              - -DskipTests
              - "-Dgs ${maven_settings}"
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: docker-signet.sk.com/onm/onm-jre-runtime:v1.0.0
  - name: local
    build:
      local:
        push: true # true: 서버 테스트 / false: 로컬 테스트
        useDockerCLI: true
      artifacts:
        # - image: feet312/sample-api # on dev server
        - image: docker-signet.sk.com/onm/onm-web 
    deploy:
      kubectl:
        manifests:
          - k8s/dev/onm-web.yaml
          
    portForward:
     - resourceType: Service
#       resourceName: commonui-service
       resourceName: onm-web
       namespace: onm-app
       port: 8900
       localPort: 8900 # *Optional*