apiVersion: apps/v1
kind: Deployment
metadata:
  name: onm-ba-deploy
  namespace: onm-dev
  labels:
    app: onm-ba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onm-ba
  template:
    metadata:
      labels:
        app: onm-ba
    spec:
      containers:
      - name: onm-ba
        image: kkswde125/onm-ba  # on server
#        image: onm-ba
        ports: 
        - name: http
          containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: onm-ba-service
  namespace: onm-dev
spec:
  # type: NodePort
  selector:
    app: onm-ba
  ports:
    - protocol: TCP
      port: 9800
      targetPort: http
      # nodePort: 32180
---